version: "3"
services:
  manage-recalls-api:
    build:
      context: .
    networks:
      - manage-recalls-api
    container_name: manage-recalls-api
    depends_on: [ postgres, fake-prisoner-offender-search-api, gotenberg ]
    ports:
      - "8080:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev
      - PRISONERSEARCH_ENDPOINT_URL=http://fake-prisoner-offender-search-api:8080
      - PRISONREGISTER_ENDPOINT_URL=http://fake-prison-register-api:8080
      - GOTENBERG_ENDPOINT_URL=http://gotenberg:3000
      - POSTGRES_HOST=postgres:5432
      - POSTGRES_DBNAME=manage_recalls
      - POSTGRES_USERNAME=ppud_user
      - POSTGRES_PASSWORD=secret

  postgres:
    image: postgres:13
    container_name: postgres_manage-recalls-api
    networks:
      - manage-recalls-api
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=ppud_user
      - POSTGRES_DB=manage_recalls

  fake-prisoner-offender-search-api:
    build: ./fake-prisoner-offender-search-api
    networks:
      - manage-recalls-api
    container_name: fake-prisoner-offender-search-api_manage-recalls-api
    ports:
      - "9092:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    command: --verbose

  fake-prison-register-api:
    build: ./fake-prison-register-api
    networks:
      - manage-recalls-api
    container_name: fake-prison-register-api_manage-recalls-api
    ports:
      - "9094:8080"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health/ping" ]
    command: --verbose

  gotenberg:
    image: thecodingmachine/gotenberg:6
    networks:
      - manage-recalls-api
    container_name: gotenberg_manage-recalls-api
    ports:
      - "9093:3000"
    environment:
      - LOG_LEVEL=DEBUG

  localstack:
    build: ./localstack-docker
    ports:
      - "4566:4566"
      - "4571:4571"
    networks:
      - manage-recalls-api
    container_name: localstack_manage-recalls-api
    environment:
      - SERVICES=s3
      - DATA_DIR=/tmp/localstack/data

networks:
  manage-recalls-api:
