version: "3"
services:
  gotenberg:
    image: thecodingmachine/gotenberg:6
    ports:
      - "9093:3000"
    networks:
      - manage-recalls-api-int-tests

  manage-recalls-api-int-tests:
    image: gradle:7-jdk16
    networks:
      - manage-recalls-api-int-tests
    volumes:
      - gradle-cache:/home/gradle/.gradle
      - .:/home/gradle/project
    container_name: manage-recalls-api-int-tests
    working_dir: /home/gradle/project
    entrypoint: [ "gradle", "documentGenerationTest", "--no-daemon" ]
    depends_on: [ gotenberg ]
    environment:
      - GOTENBERG_ENDPOINT_URL=http://gotenberg:3000

volumes:
  gradle-cache:
    external: true

networks:
  manage-recalls-api-int-tests:
