version: "3"
services:
  manage-recalls-api:
    build:
      context: .
    networks:
      manage-recalls-api
    container_name: manage-recalls-api
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ping"]
    environment:
      - SERVER_PORT=8080
      - SPRING_PROFILES_ACTIVE=dev

  gotenberg:
    image: thecodingmachine/gotenberg:6
    networks:
      manage-recalls-api
    ports:
      - "9991:3000"

networks:
  manage-recalls-api
