{{- if .Values.traefikProxy.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic-service-with-traefik.fullname" . }}
  labels:
    {{- include "generic-service-with-traefik.labels" . | nindent 4 }}
data:
  traefik.yaml: |
    ---
    global:
      checkNewVersion: false
      sendAnonymousUsage: false

    entryPoints:
      web:
        address: :{{ include "generic-service-with-traefik.traefikProxyPort" . }}
      metrics:
        address: :{{ include "generic-service-with-traefik.traefikProxyMetricsPort" . }}
      ping:
        address: :{{ include "generic-service-with-traefik.traefikProxyPingPort" . }}

    log:
      level: DEBUG
      format: common

    accessLog:
      format: common

    metrics:
      prometheus:
        entryPoint: metrics

    ping:
      entrypoint: ping

    providers:
      file:
        filename: /etc/traefik/traefik-conf.yaml
        watch: true

  traefik-conf.yaml: |
    ---
    http:
      routers:
        {{ include "generic-service-with-traefik.fullname" . }}:
          entryPoints:
            - web
          rule: PathPrefix(`/`)
          service: {{ include "generic-service-with-traefik.fullname" . }}

      services:
        {{ include "generic-service-with-traefik.fullname" . }}:
          loadBalancer:
            servers:
              - url: http://127.0.0.1:{{ .Values.image.port }}
{{- end -}}
