spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

  cache:
    type: redis
  redis:
    host: ${redis.host:localhost}
    port: ${redis.port:6379}
    password: ${redis.password:secret}
    ssl: ${redis.ssl:false}
  resolved:
    cache:
      enabled: true
      ttl: 60

logging:
  level:
    uk.gov: DEBUG

server:
  port: 8080
  shutdown: immediate

aws:
  region: eu-west-2
  credentials:
    accessKey: ANYTHING_GOES
    secretKey: ANYTHING_GOES
  s3:
    bucketName: test-manage-recalls-api
  local:
    endpoint: http://localhost:4566

manage-recalls-api:
  base-uri: http://localhost:8080

clamav:
  virus:
    scan:
      enabled: false

oauth:
  endpoint:
    url: http://localhost:9090/auth
