spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

logging:
  level:
    uk.gov: DEBUG

server:
  port: 8080
  shutdown: immediate

aws:
  region: eu-west-2
  credentials:
    access-key: ANYTHING_GOES
    secret-key: ANYTHING_GOES
  s3:
    bucket-name: test-manage-recalls-api
  local:
    endpoint: http://localhost:4566

manage-recalls-api:
  base-uri: http://localhost:8080
