spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          public-key-location: classpath:local-public-key.pub

logging:
  level:
    uk.gov: DEBUG

server:
  port: 8080
  shutdown: immediate

aws:
  region: eu-west-2
  credentials:
    accessKey: ANYTHING_GOES
    secretKey: ANYTHING_GOES
  s3.bucketName: test-manage-recalls-api
  local:
    endpoint: http://localhost:4566