version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@3.8
  gradle: circleci/gradle@2.2.0

parameters:
  alerts-slack-channel:
    type: string
    default: ppud-replacement-devs
  releases-slack-channel:
    type: string
    default: ppud-replacement-releases
  only_run_pact_workflow:
    type: boolean
    default: false
  pact_consumer_tags:
    type: string
    default: main

executors:
  local-docker:
    docker:
      - image: cimg/python:3.9
    working_directory: ~/app

jobs:
  validate:
    executor:
      name: hmpps/java
      tag: "16.0"
    steps:
      - checkout
      - gradle/with_cache:
          cache_checksum_file: "build.gradle.kts"
          steps:
            - run: ./gradlew -Dorg.gradle.jvmargs="--illegal-access=permit" -Dkotlin.daemon.jvm.options="--illegal-access=permit" check
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests
  end-to-end-tests:
    executor:
      name: hmpps/default_small
    steps:
      - run:
          name: Run end-to-end tests
          command: |
            BUILD_RESPONSE=`curl -s -u $USER_TOKEN --request POST \
                          --url https://circleci.com/api/v2/project/gh/ministryofjustice/manage-recalls-e2e-tests/pipeline \
                          --header 'content-type: application/json' \
                          --header 'x-attribution-actor-id: MANAGE_RECALLS_API' \
                          --header 'x-attribution-login: MANAGE_RECALLS_API' \
                          --data '{"branch":"main"}'`

            echo $BUILD_RESPONSE

            BUILD_ID=`echo $BUILD_RESPONSE | jq -r '.id'`

            if [[ $BUILD_ID == null ]]
            then
              echo "Unable to start test job"
              exit 1
            fi

            WAIT_LIMIT=500

            echo "Waiting upto $WAIT_LIMIT seconds for job to complete"

            TIMEOUT=`expr $SECONDS + $WAIT_LIMIT`

            STOPPED_TIME=null

            while [ $STOPPED_TIME == "null" ] && [ $SECONDS -le $TIMEOUT ]; do
              STATUS_RESPONSE=`curl -s -u '$USER_TOKEN:' --request GET --url https://circleci.com/api/v2/pipeline/$BUILD_ID/workflow`
              STOPPED_TIME=`echo $STATUS_RESPONSE | jq -r '.items[0].stopped_at'`
              STATUS=`echo $STATUS_RESPONSE | jq -r '.items[0].status'`
              sleep 15
            done

            echo "Exiting ($STATUS)..."

            if [ $STATUS == "success" ]
            then
              exit 0
            else
              exit 1
            fi

  document-generation-tests:
    executor: local-docker
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: Build and pull docker containers
          command: |
            docker-compose -f docker-compose-int-test.yml build
            docker-compose -f docker-compose-int-test.yml pull
      - run:
          name: Start docker compose and run the document generation tests
          command: |
            set -x
            docker-compose -f docker-compose-int-test.yml up --exit-code-from manage-recalls-api-int-tests
            docker cp manage-recalls-api-int-tests:/home/circleci/project/build/reports/tests/documentGenerationTest/ test-report
      - store_artifacts:
          path: test-report
          destination: local-test-summary

  verify_pact_and_publish:
    parameters:
      consumer_tags:
        type: string
    environment:
      PACTBROKER_HOST: "pact-broker-prod.apps.live-1.cloud-platform.service.justice.gov.uk"
    executor: hmpps/java
    steps:
      - checkout
      - gradle/with_cache:
          cache_checksum_file: "build.gradle.kts"
          steps:
            - run:
                command: |
                  PACT_PROVIDER_VERSION="$CIRCLE_SHA1" \
                    PACT_PROVIDER_TAG="$CIRCLE_BRANCH" \
                    PACTBROKER_CONSUMERVERSIONSELECTORS_TAGS="<< parameters.consumer_tags >>" \
                    PACT_PUBLISH_RESULTS="true" \
                    PACTBROKER_AUTH_USERNAME="$PACT_BROKER_USERNAME" \
                    PACTBROKER_AUTH_PASSWORD="$PACT_BROKER_PASSWORD" \
                    ./gradlew verifyPactAndPublish
      - store_test_results:
          path: build/test-results
      - store_artifacts:
          path: build/reports/tests

workflows:
  version: 2
  build-test-and-deploy:
    unless: << pipeline.parameters.only_run_pact_workflow >>
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/

      - document-generation-tests:
          requires:
            - validate

      - hmpps/helm_lint:
          name: helm_lint

      - hmpps/build_docker:
          name: build_docker
          publish: false
          persist_container_image: true

      - hmpps/trivy_pipeline_scan:
          name: trivy_scan_low_medium_cves
          fail_build: false
          cve_severities_to_check: UNKNOWN,LOW,MEDIUM
          requires:
            - build_docker

      - hmpps/trivy_pipeline_scan:
          name: trivy_scan
          requires:
            - build_docker

      - hmpps/publish_docker:
          name: publish_docker
          requires:
            - validate
            - helm_lint
            - trivy_scan
          filters:
            branches:
              only:
                - main

      - hmpps/deploy_env:
          name: deploy_dev
          env: dev
          context: hmpps-common-vars
          filters:
            branches:
              only:
                - main
          requires:
            - publish_docker
      - end-to-end-tests:
          requires:
            - deploy_dev
          filters:
            branches:
              only:
                - main
      - request-preprod-approval:
          type: approval
          requires:
            - end-to-end-tests
      - hmpps/deploy_env:
          name: deploy_preprod
          env: preprod
          context:
            - hmpps-common-vars
            - ppud-replacement-preprod
          requires:
            - request-preprod-approval

      - request-prod-approval:
          type: approval
          requires:
            - deploy_preprod
      - hmpps/deploy_env:
          name: deploy_prod
          env: prod
          context:
            - hmpps-common-vars
            - ppud-replacement-prod
          requires:
            - request-prod-approval
          slack_notification: true
          slack_channel_name: << pipeline.parameters.releases-slack-channel >>

  security:
    triggers:
      - schedule:
          cron: "0 7 * * 1-5"
          filters:
            branches:
              only:
                - main
    jobs:
      - hmpps/gradle_owasp_dependency_check:
          context:
            - hmpps-common-vars
          slack_channel: << pipeline.parameters.alerts-slack-channel >>
      - hmpps/veracode_policy_scan:
          context:
            - veracode-credentials
            - hmpps-common-vars
      - hmpps/trivy_latest_scan:
          context:
            - hmpps-common-vars
          slack_channel: << pipeline.parameters.alerts-slack-channel >>

  pact:
    jobs:
      - verify_pact_and_publish:
          context: hmpps-common-vars
          consumer_tags: << pipeline.parameters.pact_consumer_tags >>
