package uk.gov.justice.digital.hmpps.managerecallsapi.controller

import org.springframework.beans.factory.annotation.Autowired
import org.springframework.http.MediaType
import org.springframework.web.bind.annotation.GetMapping
import org.springframework.web.bind.annotation.RequestMapping
import org.springframework.web.bind.annotation.RestController
import uk.gov.justice.digital.hmpps.managerecallsapi.register.CourtRegisterClient
import uk.gov.justice.digital.hmpps.managerecallsapi.register.PoliceUkApiClient
import uk.gov.justice.digital.hmpps.managerecallsapi.register.Prison
import uk.gov.justice.digital.hmpps.managerecallsapi.register.PrisonRegisterClient

@RestController
@RequestMapping("/reference-data", produces = [MediaType.APPLICATION_JSON_VALUE])
class ReferenceDataController(
  @Autowired private val courtRegisterClient: CourtRegisterClient,
  @Autowired private val prisonRegisterClient: PrisonRegisterClient,
  @Autowired private val policeUkApiClient: PoliceUkApiClient,
) {

  @GetMapping("/local-delivery-units")
  fun localDeliveryUnits(): List<LocalDeliveryUnitResponse> = LocalDeliveryUnit.values()
    .map { ldu -> LocalDeliveryUnitResponse(ldu.name, ldu.label) }.toList()

  @GetMapping("/courts")
  fun courts(): List<CourtRegisterClient.Court> = courtRegisterClient.getAllCourts().block()!!

  @GetMapping("/prisons")
  fun prisons(): List<Prison> = prisonRegisterClient.getAllPrisons().block()!!

  @GetMapping("/police-forces")
  fun policeForces(): List<PoliceUkApiClient.PoliceForce> = policeUkApiClient.getAllPoliceForces().block()!!

  @GetMapping("/index-offences")
  fun indexOffences(): List<IndexOffence> = IndexOffenceEnum.values()
    .map { offence -> IndexOffence(offence.name, offence.label) }.toList()
}

data class IndexOffence(val id: String, val name: String)

// TODO: migrate name, label to id, name to be closer to e.g. courts and prisons responses
data class LocalDeliveryUnitResponse(val name: String, val label: String)

@Suppress("unused")
enum class LocalDeliveryUnit(val label: String) {
  CENTRAL_AUDIT_TEAM("Central Audit Team"),
  CHANNEL_ISLANDS("Channel Islands"),
  ISLE_OF_MAN("Isle of Man"),
  NORTHERN_IRELAND("Northern Ireland"),
  NOT_APPLICABLE("Not applicable"),
  NOT_SPECIFIED("Not specified"),
  PS_BARKING_DAGENHAM_HAVERING("PS - Barking, Dagenham & Havering"),
  PS_BARNET("PS - Barnet"),
  PS_BARNSLEY("PS - Barnsley"),
  PS_BATH_AND_NORTH_SOMERSET("PS - Bath and North Somerset"),
  PS_BEDFORDSHIRE("PS - Bedfordshire"),
  PS_BEXLEY("PS - Bexley"),
  PS_BIRMINGHAM_CENTRAL_AND_SOUTH("PS - Birmingham Central and South"),
  PS_BIRMINGHAM_NORTH_AND_EAST("PS - Birmingham North and East"),
  PS_BLACKBURN_AND_DARWEN("PS - Blackburn and Darwen"),
  PS_BLACKPOOL("PS - Blackpool"),
  PS_BOLTON("PS - Bolton"),
  PS_BRADFORD("PS - Bradford"),
  PS_BRENT("PS - Brent"),
  PS_BRIGHTON_AND_EAST_SUSSEX("PS - Brighton and East Sussex"),
  PS_BRISTOL_AND_SOUTH_GLOUCESTERSHIRE("PS - Bristol and South Gloucestershire"),
  PS_BROMLEY("PS - Bromley"),
  PS_BUCKINGHAMSHIRE_M_KEYNES("PS - Buckinghamshire & M Keynes"),
  PS_BURNLEY("PS - Burnley"),
  PS_BURY("PS - Bury"),
  PS_CALDERDALE("PS - Calderdale"),
  PS_CAMBRIDGESHIRE_AND_PETERBOROUGH("PS - Cambridgeshire and Peterborough"),
  PS_CAMDEN_ISLINGTON("PS - Camden & Islington"),
  PS_CARDIFF_AND_VALE("PS - Cardiff and Vale"),
  PS_CHESTER("PS - Chester"),
  PS_CHORLEY("PS - Chorley"),
  PS_CORNWALL_AND_ISLES_OF_SCILLY("PS - Cornwall and Isles of Scilly"),
  PS_COVENTRY("PS - Coventry"),
  PS_CREWE("PS - Crewe"),
  PS_CROYDON("PS - Croydon"),
  PS_CUMBRIA("PS - Cumbria"),
  PS_CWM_TAF_MORGANNWG("PS - Cwm Taf Morgannwg"),
  PS_DERBY_CITY("PS - Derby City"),
  PS_DERBYSHIRE("PS - Derbyshire"),
  PS_DEVON_AND_TORBAY("PS - Devon and Torbay"),
  PS_DONCASTER("PS - Doncaster"),
  PS_DORSET("PS - Dorset"),
  PS_DUDLEY("PS - Dudley"),
  PS_DURHAM("PS - Durham"),
  PS_DYFED_POWYS("PS - Dyfed-Powys"),
  PS_EALING("PS - Ealing"),
  PS_EAST_BERKSHIRE("PS - East Berkshire"),
  PS_EAST_CHESHIRE("PS - East Cheshire"),
  PS_EAST_KENT("PS - East Kent"),
  PS_EAST_LANCASHIRE("PS - East Lancashire"),
  PS_EAST_RIDING("PS - East Riding"),
  PS_ENFIELD("PS - Enfield"),
  PS_ESSEX_NORTH("PS - Essex North"),
  PS_ESSEX_SOUTH("PS - Essex South"),
  PS_GATESHEAD("PS - Gateshead"),
  PS_GLOUCESTERSHIRE("PS - Gloucestershire"),
  PS_GREENWICH("PS - Greenwich"),
  PS_GWENT("PS - Gwent"),
  PS_HACKNEY("PS - Hackney"),
  PS_HALTON("PS - Halton"),
  PS_HAMMERSMITH_FULHAM("PS - Hammersmith & Fulham"),
  PS_HAMPSHIRE_NORTH_AND_EAST("PS - Hampshire North and East"),
  PS_HARINGEY("PS - Haringey"),
  PS_HARROW("PS - Harrow"),
  PS_HARTLEPOOL("PS - Hartlepool"),
  PS_HEREFORDSHIRE("PS - Herefordshire"),
  PS_HERTFORDSHIRE("PS - Hertfordshire"),
  PS_HILLINGDON("PS - Hillingdon"),
  PS_HOUNSLOW("PS - Hounslow"),
  PS_HULL("PS - Hull"),
  PS_KENSINGTON_CHELSEA_WESTMINSTER("PS - Kensington, Chelsea & Westminster"),
  PS_KINGSTON_RICHMOND("PS - Kingston & Richmond"),
  PS_KIRKLEES("PS - Kirklees"),
  PS_KNOWSLEY("PS - Knowsley"),
  PS_LAMBETH("PS - Lambeth"),
  PS_LANCASTER("PS - Lancaster"),
  PS_LEEDS("PS - Leeds"),
  PS_LEICESTER("PS - Leicester"),
  PS_LEICESTERSHIRE_AND_RUTLAND("PS - Leicestershire and Rutland"),
  PS_LEWISHAM("PS - Lewisham"),
  PS_LINCOLNSHIRE_EAST("PS - Lincolnshire East"),
  PS_LINCOLNSHIRE_WEST("PS - Lincolnshire West"),
  PS_LIVERPOOL_NORTH("PS - Liverpool North"),
  PS_LIVERPOOL_SOUTH("PS - Liverpool South"),
  PS_MACCLESFIELD("PS - Macclesfield"),
  PS_MANCHESTER_NORTH("PS - Manchester North"),
  PS_MANCHESTER_SOUTH("PS - Manchester South"),
  PS_MERTON_SUTTON("PS - Merton & Sutton"),
  PS_MIDDLESBROUGH("PS - Middlesbrough"),
  PS_NEWCASTLE_UPON_TYNE("PS - Newcastle Upon Tyne"),
  PS_NEWHAM("PS - Newham"),
  PS_NORFOLK("PS - Norfolk"),
  PS_NORTH_DURHAM("PS - North Durham"),
  PS_NORTH_EAST_LINCOLNSHIRE("PS - North East Lincolnshire"),
  PS_NORTH_LINCOLNSHIRE("PS - North Lincolnshire"),
  PS_NORTH_TYNESIDE("PS - North Tyneside"),
  PS_NORTH_WALES("PS - North Wales"),
  PS_NORTH_YORKSHIRE("PS - North Yorkshire"),
  PS_NORTHAMPTONSHIRE("PS - Northamptonshire"),
  PS_NORTHUMBERLAND("PS - Northumberland"),
  PS_NORTHWICH("PS - Northwich"),
  PS_NOTTINGHAM("PS - Nottingham"),
  PS_NOTTINGHAMSHIRE("PS - Nottinghamshire"),
  PS_OLDHAM("PS - Oldham"),
  PS_OXFORDSHIRE("PS - Oxfordshire"),
  PS_PLYMOUTH("PS - Plymouth"),
  PS_PORTSMOUTH_AND_IOW("PS - Portsmouth and IoW"),
  PS_PRESTON("PS - Preston"),
  PS_REDBRIDGE("PS - Redbridge"),
  PS_REDCAR_CLEVELAND("PS - Redcar Cleveland"),
  PS_ROCHDALE("PS - Rochdale"),
  PS_ROTHERHAM("PS - Rotherham"),
  PS_SALFORD("PS - Salford"),
  PS_SANDWELL("PS - Sandwell"),
  PS_SEFTON("PS - Sefton"),
  PS_SHEFFIELD("PS - Sheffield"),
  PS_SHROPSHIRE("PS - Shropshire"),
  PS_SKELMERSDALE("PS - Skelmersdale"),
  PS_SOLIHULL("PS - Solihull"),
  PS_SOMERSET("PS - Somerset"),
  PS_SOUTH_DURHAM("PS - South Durham"),
  PS_SOUTH_TYNESIDE("PS - South Tyneside"),
  PS_SOUTHAMPTON_EASTLEIGH_AND_NEW_FOREST("PS - Southampton, Eastleigh and New Forest"),
  PS_SOUTHWARK("PS - Southwark"),
  PS_ST_HELENS("PS - St Helens"),
  PS_STAFFORDSHIRE("PS - Staffordshire"),
  PS_STOCKPORT("PS - Stockport"),
  PS_STOCKTON("PS - Stockton"),
  PS_STOKE("PS - Stoke"),
  PS_SUFFOLK("PS - Suffolk"),
  PS_SUNDERLAND("PS - Sunderland"),
  PS_SURREY("PS - Surrey"),
  PS_SWANSEA_NEATH_AND_PORT_TALBOT("PS - Swansea, Neath and Port-Talbot"),
  PS_SWINDON_AND_WILTSHIRE("PS - Swindon and Wiltshire"),
  PS_TAMESIDE("PS - Tameside"),
  PS_TELFORD("PS - Telford"),
  PS_TOWER_HAMLETS("PS - Tower Hamlets"),
  PS_TRAFFORD("PS - Trafford"),
  PS_WAKEFIELD("PS - Wakefield"),
  PS_WALSALL("PS - Walsall"),
  PS_WALTHAM_FOREST("PS - Waltham Forest"),
  PS_WANDSWORTH("PS - Wandsworth"),
  PS_WARRINGTON("PS - Warrington"),
  PS_WARWICKSHIRE("PS - Warwickshire"),
  PS_WEST_BERKSHIRE("PS - West Berkshire"),
  PS_WEST_CHESHIRE("PS - West Cheshire"),
  PS_WEST_KENT("PS - West Kent"),
  PS_WEST_SUSSEX("PS - West Sussex"),
  PS_WIGAN("PS - Wigan"),
  PS_WIRRAL("PS - Wirral"),
  PS_WOLVERHAMPTON("PS - Wolverhampton"),
  PS_WORCESTERSHIRE("PS - Worcestershire"),
  PS_YORK("PS - York"),
  REGIONAL_CT_ADMIN("Regional CT Admin"),
  REPUBLIC_OF_IRELAND("Republic of Ireland"),
  SCOTLAND("Scotland"),
  YOT_SEE_COMMENTS("YOT - See Comments")
}

@Suppress("unused")
enum class IndexOffenceGroupEnum(val label: String) {
  OFFENCE_GROUP_GROUP("Offence Group"),
  BURGLARY_GROUP("Burglary"),
  DRUG_OFFENCES_GROUP("Drug Offences"),
  FRAUD_AND_FORGERY_GROUP("Fraud & Forgery"),
  MOTORING_OFFENCES_GROUP("Motoring Offences"),
  NOT_APPLICABLE_GROUP("Not Applicable"),
  NOT_SPECIFIED_GROUP("Not Specified"),
  OTHER_GROUP("Other"),
  ROBBERY_GROUP("Robbery"),
  SEXUAL_OFFENCE_GROUP("Sexual Offence"),
  SEXUAL_OFFENCE_SERIOUS_GROUP("Sexual Offence – Serious"),
  TERRORISM_GROUP("Terrorism"),
  THEFT_AND_HANDLING_GROUP("Theft & Handling"),
  VIOLENCE_AGAINST_THE_PERSON_GROUP("Violence Against The Person"),
  VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP("Violence Against The Person - Serious"),
}

// Note: enum name becomes instance id on API to be closer to e.g. courts and prisons responses
@Suppress("unused")
enum class IndexOffenceEnum(val label: String, val group: IndexOffenceGroupEnum) {
  ABDUCTION("Abduction", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  ABDUCTION_SEXUAL_OFFENCES_ACT_1956("ABDUCTION (SEXUAL OFFENCES ACT 1956)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  ABDUCTION_OF_WOMAN_BY_FORCE_OR_FOR_THE_SAKE_OF_HER("Abduction of woman by force or for the sake of her", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  ABH("ABH", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  ABSCOND("ABSCOND", IndexOffenceGroupEnum.OTHER_GROUP),
  ABSTRACTING_ELECTRICITY("ABSTRACTING ELECTRICITY", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  ABUSE_OF_A_POSITION_OF_TRUST_SEC_3_SOA_ACT_2000("ABUSE OF A POSITION OF TRUST SEC 3 SO(A) ACT 2000", IndexOffenceGroupEnum.OTHER_GROUP),
  ADMINISTER_DRUGS("ADMINISTER DRUGS", IndexOffenceGroupEnum.DRUG_OFFENCES_GROUP),
  ADMINISTERING_A_SUBSTANCE_WITH_INTENT_SECTION_61_OF_THE_SEXUAL_OFFENCES_ACT_2003("Administering a substance with intent (section 61 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  AFFILIATION_ORDERS("AFFILIATION ORDERS", IndexOffenceGroupEnum.OTHER_GROUP),
  AFFRAY("AFFRAY", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  AGGRAVATED_ASSAULT("AGGRAVATED ASSAULT", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  AGGRAVATED_BURGLARY_SECTION_10_OF_THE_THEFT_ACT_1968("Aggravated burglary (section 10 of the Theft Act 1968)", IndexOffenceGroupEnum.BURGLARY_GROUP),
  AGGRAVATED_DRUNKENESS("AGGRAVATED DRUNKENESS", IndexOffenceGroupEnum.OTHER_GROUP),
  AGGRAVATED_THEFT("Aggravated theft", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  AGGRAVATED_VEHICLE_TAKING("Aggravated vehicle taking", IndexOffenceGroupEnum.ROBBERY_GROUP),
  AGGRAVATED_VEHICLE_TAKING_INVOLVING_AN_ACCIDENT_WHICH_CAUSED_THE_DEATH_OF_ANY_PERSON_SECTION_12A_OF_THE_THEFT_ACT_1968("Aggravated vehicle-taking involving an accident which caused the death of any person (Section 12A of the Theft Act 1968)", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  AIDING_OR_ABETTING_A_SERIOUS_SEX_OFFENCE("Aiding or abetting a serious sex offence", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  AIDING_ABETTING_COUNSELLING_PROCURING_OR_INCITING_THE_COMMISSION_OR_CONSPIRING_TO_COMMIT_OR_ATTEMPTING_TO_COMMIT_AN_SFO_OFFENCE("Aiding, abetting, counselling, procuring or inciting the commission, or conspiring to commit, or attempting to commit an SFO offence", IndexOffenceGroupEnum.OTHER_GROUP),
  ARMED_ROBBERY("Armed Robbery", IndexOffenceGroupEnum.ROBBERY_GROUP),
  ARRANGING_OR_FACILITATING_CHILD_PROSTITUTION_OR_PORNOGRAPHY_SECTION_50_OF_THE_SEXUAL_OFFENCES_ACT_2003("Arranging or facilitating child prostitution or pornography (section 50 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  ARRANGING_OR_FACILITATING_COMMISSION_OF_A_CHILD_SEX_OFFENCE_SECTION_14_OF_THE_SEXUAL_OFFENCES_ACT_2003("Arranging or facilitating commission of a child sex offence (section 14 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  ARSON_SECTION_1_OF_THE_CRIMINAL_DAMAGE_ACT_1971("Arson (section 1 of the Criminal Damage Act 1971)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  ARSON_WITH_INTENT("ARSON WITH INTENT", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  ASSAULT_A_POLICE_OFFICER("ASSAULT A POLICE OFFICER", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  ASSAULT_BY_PENETRATION_SECTION_2_OF_THE_SEXUAL_OFFENCES_ACT_2003("Assault by penetration (section 2 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  ASSAULT_COURT_PRISON_OFFICER("ASSAULT COURT/PRISON OFFICER", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  ASSAULT_OCCASIONING_ABH("ASSAULT OCCASIONING ABH", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  ASSAULT_OF_A_CHILD_UNDER_13_BY_PENETRATION_SECTION_6_OF_THE_SEXUAL_OFFENCES_ACT_2003("Assault of a child under 13 by penetration (section 6 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  ASSAULT_WITH_INTENT_TO_CAUSE_ABH("ASSAULT WITH INTENT TO CAUSE ABH", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  ASSAULT_WITH_INTENT_TO_CAUSE_GBH("ASSAULT WITH INTENT TO CAUSE GBH", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  ASSAULT_WITH_INTENT_TO_COMMIT_BUGGERY_SECTION_16_OF_THE_SEXUAL_OFFENCES_ACT_1956("Assault with intent to commit buggery (section 16 of the Sexual Offences Act 1956)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  ASSAULT_WITH_INTENT_TO_RESIST_ARREST("ASSAULT WITH INTENT TO RESIST ARREST", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  ASSISTING_A_GIRL_TO_MUTILATE_HER_OWN_GENITALIA_SECTION_2_OF_THE_FEMALE_GENITAL_MUTILATION_ACT_2003("Assisting a girl to mutilate her own genitalia (section 2 of the Female Genital Mutilation Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  ASSISTING_A_NON_UK_PERSON_TO_MUTILATE_OVERSEAS_A_GIRLS_GENITALIA_SECTION_3_OF_THE_FEMALE_GENITAL_MUTILATION_ACT_2003_A_AIDING_ABETTING_COUNSELLING_PROCURING_OR_INCITING_THE_COMMISSION_OF_AN_OFFENCE_SPECIFIED_IN_THIS_PART_OF_THIS_SCHEDULE_B_CONSPIRING_TO_COMMIT_AN_OFFENCE_SO_SPECIFIED_C_ATTEMPTING_TO_COMMIT_AN_OFFENCE_SO_SPECIFIED("Assisting a non-UK person to mutilate overseas a girl's genitalia (section 3 of the Female Genital Mutilation Act 2003) (a) Aiding, abetting, counselling, procuring or inciting the commission of an offence specified in this Part of this Schedule (b) Conspiring to commit an offence so specified (c) attempting to commit an offence so specified", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  ASSISTING_ILLEGAL_IMMIGRANTS("ASSISTING ILLEGAL IMMIGRANTS", IndexOffenceGroupEnum.OTHER_GROUP),
  ATTEMPT_TO_CAUSE_EXPLOSION_OR_MAKING_OR_KEEPING_EXPLOSIVE_WITH_INTENT_TO_ENDANGER_LIFE_OR_PROPERTY_SECTION_3_OF_THE_EXPLOSIVE_SUBSTANCES_ACT_1883("Attempt to cause explosion, or making or keeping explosive with intent to endanger life or property (section 3 of the Explosive Substances Act 1883)", IndexOffenceGroupEnum.TERRORISM_GROUP),
  ATTEMPT_TO_COMMIT_A_KIDNAP("ATTEMPT TO COMMIT A KIDNAP", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  ATTEMPT_TO_COMMIT_MURDER_OR_A_CONSPIRACY_TO_COMMIT_MURDER("Attempt to commit murder or a conspiracy to commit murder", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  ATTEMPT_TO_COMMIT_RAPE("ATTEMPT TO COMMIT RAPE", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  ATTEMPT_TO_COMMIT_THEFT("ATTEMPT TO COMMIT THEFT", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  ATTEMPT_TO_PERVERT_THE_COURSE_OF_JUSTICE("ATTEMPT TO PERVERT THE COURSE OF JUSTICE", IndexOffenceGroupEnum.OTHER_GROUP),
  ATTEMPTED_BUGGERY("ATTEMPTED BUGGERY", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  ATTEMPTED_BURGLARY("ATTEMPTED BURGLARY", IndexOffenceGroupEnum.BURGLARY_GROUP),
  ATTEMPTED_BURGLARY_WITH_INTENT_TO_STEAL_IN_DWELLING("Attempted burglary (with intent to steal - in dwelling)", IndexOffenceGroupEnum.BURGLARY_GROUP),
  ATTEMPTED_DECEPTION("ATTEMPTED DECEPTION", IndexOffenceGroupEnum.FRAUD_AND_FORGERY_GROUP),
  ATTEMPTED_MURDER("ATTEMPTED MURDER", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  ATTEMPTED_ROBBERY("ATTEMPTED ROBBERY", IndexOffenceGroupEnum.ROBBERY_GROUP),
  ATTEMPTING_TO_CHOKE_SUFFOCATE_OR_STRANGLE_IN_ORDER_TO_COMMIT_OR_ASSIST_IN_COMMITTING_AN_INDICTABLE_OFFENCE_SECTION_21_OF_THE_OFFENCES_AGAINST_THE_PERSON_ACT_1861("Attempting to choke, suffocate or strangle in order to commit or assist in committing an indictable offence (section 21 of the Offences Against the Person Act 1861)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  BAIL_ACT_OFFENCES("Bail Act Offences", IndexOffenceGroupEnum.OTHER_GROUP),
  BATTERY("Battery", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  BEING_CARRIED_IN_A_STOLEN_VEHICLE("BEING CARRIED IN A STOLEN VEHICLE", IndexOffenceGroupEnum.MOTORING_OFFENCES_GROUP),
  BETTING_GAMING_AND_LOTTERIES("BETTING GAMING AND LOTTERIES", IndexOffenceGroupEnum.OTHER_GROUP),
  BIGAMY("BIGAMY", IndexOffenceGroupEnum.OTHER_GROUP),
  BLACKMAIL("BLACKMAIL", IndexOffenceGroupEnum.OTHER_GROUP),
  BOMB_HOAX("BOMB HOAX", IndexOffenceGroupEnum.TERRORISM_GROUP),
  BREACH_OF_ANTI_SOCIAL_BEHAVIOUR_ORDER("Breach of anti social behaviour order", IndexOffenceGroupEnum.OTHER_GROUP),
  BREACH_OF_ATTENDANCE_ORDER("BREACH OF ATTENDANCE ORDER", IndexOffenceGroupEnum.OTHER_GROUP),
  BREACH_OF_BAIL("BREACH OF BAIL", IndexOffenceGroupEnum.OTHER_GROUP),
  BREACH_OF_COMBINATION_ORDER("BREACH OF COMBINATION ORDER", IndexOffenceGroupEnum.OTHER_GROUP),
  BREACH_OF_COMMUNITY_SERVICE_ORDER("BREACH OF COMMUNITY SERVICE ORDER", IndexOffenceGroupEnum.OTHER_GROUP),
  BREACH_OF_CONDITIONAL_DISCHARGE("BREACH OF CONDITIONAL DISCHARGE", IndexOffenceGroupEnum.OTHER_GROUP),
  BREACH_OF_COURT_ORDER("Breach of Court Order", IndexOffenceGroupEnum.OTHER_GROUP),
  BREACH_OF_DRUG_TESTING_AND_TREATMENT_ORDER("BREACH OF DRUG TESTING AND TREATMENT ORDER", IndexOffenceGroupEnum.OTHER_GROUP),
  BREACH_OF_PROBATION_ORDER("BREACH OF PROBATION ORDER", IndexOffenceGroupEnum.OTHER_GROUP),
  BREACH_OF_RECOGNISANCE("BREACH OF RECOGNISANCE", IndexOffenceGroupEnum.OTHER_GROUP),
  BREACH_OF_RESTRAINING_ORDER("BREACH OF RESTRAINING ORDER", IndexOffenceGroupEnum.OTHER_GROUP),
  BREACH_OF_SEXUAL_OFFENCES_PREVENTION_ORDER_SOPO("Breach of Sexual Offences Prevention Order (SOPO)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  BREACH_OF_SUPERVISION_ORDER("BREACH OF SUPERVISION ORDER", IndexOffenceGroupEnum.OTHER_GROUP),
  BREACH_OF_SUSPENDED_SENTENCE("BREACH OF SUSPENDED SENTENCE", IndexOffenceGroupEnum.OTHER_GROUP),
  BREACH_OF_THE_PEACE("Breach of the Peace", IndexOffenceGroupEnum.OTHER_GROUP),
  BREAK_AND_ENTRY("BREAK AND ENTRY", IndexOffenceGroupEnum.BURGLARY_GROUP),
  BUGGERY("BUGGERY", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  BURGLARY("BURGLARY", IndexOffenceGroupEnum.BURGLARY_GROUP),
  BURGLARY_STEALING_IN_DWELLING("Burglary (stealing - in dwelling)", IndexOffenceGroupEnum.BURGLARY_GROUP),
  BURGLARY_OF_A_DWELLING_PLACE("BURGLARY OF A DWELLING PLACE", IndexOffenceGroupEnum.BURGLARY_GROUP),
  BURGLARY_OF_NON_DWELLING_PLACE("BURGLARY OF NON-DWELLING PLACE", IndexOffenceGroupEnum.BURGLARY_GROUP),
  BURGLARY_WITH_INTENT_TO_A_INFLICT_GRIEVOUS_BODILY_HARM_ON_A_PERSON_OR_B_DO_UNLAWFUL_DAMAGE_TO_A_BUILDING_OR_ANYTHING_IN_IT_SECTION_9_OF_THE_THEFT_ACT_1968("Burglary with intent to- (a) inflict grievous bodily harm on a person or (b) do unlawful damage to a building or anything in it (section 9 of the Theft Act 1968)", IndexOffenceGroupEnum.BURGLARY_GROUP),
  BURGLARY_WITH_INTENT_TO_COMMIT_RAPE_SECTION_9_OF_THE_THEFT_ACT_1968("Burglary with intent to commit rape (section 9 of the Theft Act 1968)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  CARE_WORKERS_CAUSING_OR_INCITING_SEXUAL_ACTIVITY_SECTION_39_OF_THE_SEXUAL_OFFENCES_ACT_2003("Care workers: causing or inciting sexual activity (section 39 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  CARE_WORKERS_SEXUAL_ACTIVITY_WITH_A_PERSON_WITH_A_MENTAL_DISORDER_SECTION_38_OF_THE_SEXUAL_OFFENCES_ACT_2003("Care workers: sexual activity with a person with a mental disorder (section 38 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  CARRYING_A_FIREARM_WITH_CRIMINAL_INTENT_SECTION_18_OF_THE_FIREARMS_ACT_1968("Carrying a firearm with criminal intent (section 18 of the Firearms Act 1968)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  CAUSE_A_FEMALE_TO_ENGAGED_IN_SEXUAL_ACTIVITY_WITHOUT_CONSENT_PENETRATION("Cause a female to engaged in sexual activity without consent - penetration", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  CAUSE_A_MALE_TO_ENGAGED_IN_SEXUAL_ACTIVITY_WITHOUT_CONSENT_PENETRATION("Cause a male to engaged in sexual activity without consent - penetration", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  CAUSE_INCITE_A_PERSON_WITH_A_MENTAL_DISORDER_LEARNING_DISABILITY_TO_ENGAGE_IN_SEXUAL_ACTIVITY_CARE_WORKER_PENETRATION_OF_ANUS_VAGINA_MOUTH_BY_PENIS_PART_OF_BODY("Cause/incite a person with a mental disorder/learning disability to engage in sexual activity - care worker - penetration of anus, vagina, mouth by penis/part of body", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  CAUSING_A_CHILD_TO_WATCH_A_SEXUAL_ACT_SECTION_12_OF_THE_SEXUAL_OFFENCES_ACT_2003("Causing a child to watch a sexual act (section 12 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  CAUSING_A_PERSON_TO_ENGAGE_IN_SEXUAL_ACTIVITY_WITHOUT_CONSENT_SECTION_4_OF_THE_SEXUAL_OFFENCES_ACT_2003("Causing a person to engage in sexual activity without consent (section 4 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  CAUSING_A_PERSON_WITH_A_MENTAL_DISORDER_IMPEDING_CHOICE_TO_WATCH_A_SEXUAL_ACT_SECTION_33_OF_THE_SEXUAL_OFFENCES_ACT_2003("Causing a person with a mental disorder impeding choice to watch a sexual act (section 33 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  CAUSING_A_PERSON_WITH_A_MENTAL_DISORDER_TO_ENGAGE_IN_OR_AGREE_TO_ENGAGE_IN_SEXUAL_ACTIVITY_BY_INDUCEMENT_THREAT_OR_DECEPTION_SECTION_35_OF_THE_SEXUAL_OFFENCES_ACT_2003("Causing a person with a mental disorder to engage in or agree to engage in sexual activity by inducement, threat or deception (section 35 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  CAUSING_A_PERSON_WITH_A_MENTAL_DISORDER_TO_WATCH_A_SEXUAL_ACT_BY_INDUCEMENT_THREAT_OR_DECEPTION_SECTION_37_OF_THE_SEXUAL_OFFENCES_ACT_2003("Causing a person with a mental disorder to watch a sexual act by inducement, threat or deception (section 37 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  CAUSING_AN_EXPLOSION_OR_PLACING_EXPLOSIVE("CAUSING AN EXPLOSION OR PLACING EXPLOSIVE", IndexOffenceGroupEnum.TERRORISM_GROUP),
  CAUSING_BODILY_INJURY_BY_EXPLOSIVES_SECTION_28_OF_THE_OFFENCES_AGAINST_THE_PERSON_ACT_1861("Causing bodily injury by explosives (section 28 of the Offences Against the Person Act 1861)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  CAUSING_DEATH_BY_CARELESS_DRIVING_WHEN_UNDER_INFLUENCE_OF_DRINK_OR_DRUGS_SECTION_3A_OF_THE_ROAD_TRAFFIC_ACT_1988("Causing death by careless driving when under influence of drink or drugs (section 3A of the Road Traffic Act 1988)", IndexOffenceGroupEnum.DRUG_OFFENCES_GROUP),
  CAUSING_DEATH_BY_DANGEROUS_DRIVING_SECTION_1_OF_THE_ROAD_TRAFFIC_ACT_1988("Causing death by dangerous driving (section 1 of the Road Traffic Act 1988)", IndexOffenceGroupEnum.MOTORING_OFFENCES_GROUP),
  CAUSING_EXPLOSION_LIKELY_TO_ENDANGER_LIFE_OR_PROPERTY_SECTION_2_OF_THE_EXPLOSIVE_SUBSTANCES_ACT_1883("Causing explosion likely to endanger life or property (section 2 of the Explosive Substances Act 1883)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  CAUSING_OR_ALLOWING_THE_DEATH_OF_A_CHILD_OR_VULNERABLE_ADULT_ALSO_CALLED_FAMILIAL_HOMICIDE_SECTION_5_OF_THE_DOMESTIC_VIOLENCE_CRIME_AND_VICTIMS_ACT_2004("Causing or allowing the death of a child or vulnerable adult, also called --familial homicide-- (Section 5 of the Domestic Violence, Crime and Victims Act 2004)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  CAUSING_OR_INCITING_A_CHILD_TO_ENGAGE_IN_SEXUAL_ACTIVITY_SECTION_10_OF_THE_SEXUAL_OFFENCES_ACT_2003("Causing or inciting a child to engage in sexual activity (section 10 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  CAUSING_OR_INCITING_A_PERSON_WITH_A_MENTAL_DISORDER_IMPEDING_CHOICE_TO_ENGAGE_IN_SEXUAL_ACTIVITY_SECTION_31_OF_THE_SEXUAL_OFFENCES_ACT_2003("Causing or inciting a person with a mental disorder impeding choice to engage in sexual activity (section 31 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  CAUSING_OR_INCITING_CHILD_PROSTITUTION_OR_PORNOGRAPHY_SECTION_48_OF_THE_SEXUAL_OFFENCES_ACT_2003("Causing or inciting child prostitution or pornography (section 48 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  CHILD_ABDUCTION("Child Abduction", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  CHILD_DESTRUCTION("Child Destruction", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  CHILD_DESTRUCTION_SECTION_1_OF_THE_INFANT_LIFE_PRESERVATION_ACT_1929("Child destruction (section 1 of the Infant Life (Preservation) Act 1929)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  CHOKING_WITH_INTENT_TO_ROBBERY("Choking with intent to Robbery", IndexOffenceGroupEnum.ROBBERY_GROUP),
  COMMIT_ANY_OFFENCE_BY_KIDNAP_FALSE_IMPRISONMENT_WITH_INTENT_COMMIT_A_SEXUAL_OFFENCE("Commit any offence by kidnap /false imprisonment with intent commit a sexual offence", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  COMMITTING_AN_OFFENCE_WITH_INTENT_TO_COMMIT_A_SEXUAL_OFFENCE_SECTION_62_OF_THE_SEXUAL_OFFENCES_ACT_2003("Committing an offence with intent to commit a sexual offence (section 62 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  COMMON_ASSAULT("COMMON ASSAULT", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  CONSPIRACY_TO_CAUSE_AN_AFFRAY("CONSPIRACY TO CAUSE AN AFFRAY", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  CONSPIRACY_TO_CAUSE_AN_EXPLOSION("CONSPIRACY TO CAUSE AN EXPLOSION", IndexOffenceGroupEnum.TERRORISM_GROUP),
  CONSPIRACY_TO_COMMIT_A_KIDNAP("CONSPIRACY TO COMMIT A KIDNAP", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  CONSPIRACY_TO_COMMIT_BURGLARY("CONSPIRACY TO COMMIT BURGLARY", IndexOffenceGroupEnum.BURGLARY_GROUP),
  CONSPIRACY_TO_COMMIT_BURGLARY_WITH_INTENT_TO_STEAL_IN_DWELLING("Conspiracy to commit burglary (with intent to steal - in dwelling)", IndexOffenceGroupEnum.BURGLARY_GROUP),
  CONSPIRACY_TO_COMMIT_ROBBERY("CONSPIRACY TO COMMIT ROBBERY", IndexOffenceGroupEnum.ROBBERY_GROUP),
  CONSPIRACY_TO_COMMIT_THEFT("CONSPIRACY TO COMMIT THEFT", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  CONSPIRACY_TO_DEFRAUD("CONSPIRACY TO DEFRAUD", IndexOffenceGroupEnum.FRAUD_AND_FORGERY_GROUP),
  CONSPIRACY_TO_HI_JACK("CONSPIRACY TO HI-JACK", IndexOffenceGroupEnum.TERRORISM_GROUP),
  CONSPIRACY_TO_IMPORT_DRUGS("CONSPIRACY TO IMPORT DRUGS", IndexOffenceGroupEnum.DRUG_OFFENCES_GROUP),
  CONSPIRACY_TO_RIOT("CONSPIRACY TO RIOT", IndexOffenceGroupEnum.OTHER_GROUP),
  CONSPIRACY_TO_SUPPLY_DRUGS("CONSPIRACY TO SUPPLY DRUGS", IndexOffenceGroupEnum.DRUG_OFFENCES_GROUP),
  CONSPIRACYAIDINGABETTINGOR_INCITEMENT_TO_MURDER("CONSPIRACY,AIDING,ABETTING,OR INCITEMENT TO MURDER", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  CONTEMPT_OF_COURT("CONTEMPT OF COURT", IndexOffenceGroupEnum.OTHER_GROUP),
  CONTROLLING_A_CHILD_PROSTITUTE_OR_A_CHILD_INVOLVED_IN_PORNOGRAPHY_SECTION_49_OF_THE_SEXUAL_OFFENCES_ACT_2003("Controlling a child prostitute or a child involved in pornography (section 49 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  COSTS_IN_OTHER_PROCEEDINGS_NOT_MC("COSTS IN OTHER PROCEEDINGS/NOT MC", IndexOffenceGroupEnum.OTHER_GROUP),
  CRIMINAL_ATTEMPTS_ACT("CRIMINAL ATTEMPTS ACT", IndexOffenceGroupEnum.OTHER_GROUP),
  CRIMINAL_BANKRUPTCY("CRIMINAL BANKRUPTCY", IndexOffenceGroupEnum.OTHER_GROUP),
  CRIMINAL_DAMAGE("CRIMINAL DAMAGE", IndexOffenceGroupEnum.OTHER_GROUP),
  CRUELTY_TO_ANIMALS("CRUELTY TO ANIMALS", IndexOffenceGroupEnum.OTHER_GROUP),
  CRUELTY_TO_CHILDREN_SECTION_1_OF_THE_CHILDREN_AND_YOUNG_PERSONS_ACT_1933("Cruelty to children (section 1 of the Children and Young Persons Act 1933)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  CRUELTY_TO_OR_NEGLECT_OF_CHILDREN("CRUELTY TO OR NEGLECT OF CHILDREN", IndexOffenceGroupEnum.OTHER_GROUP),
  CUSTOMS_AND_EXCISE_EVASION("CUSTOMS AND EXCISE EVASION", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  CUSTOMS_EVASION_DRUGS_RELATED("CUSTOMS EVASION (DRUGS RELATED)", IndexOffenceGroupEnum.DRUG_OFFENCES_GROUP),
  CUSTOMS_EVASION_NOT_DRUGS_RELATED("CUSTOMS EVASION (NOT DRUGS RELATED)", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  DEATH_BY_RECKLESS_DRIVING("DEATH BY RECKLESS DRIVING", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  DEBTS("DEBTS", IndexOffenceGroupEnum.OTHER_GROUP),
  DECEPTION("DECEPTION", IndexOffenceGroupEnum.FRAUD_AND_FORGERY_GROUP),
  DESTROYING_FIXED_PLATFORMS_OR_ENDANGERING_THEIR_SAFETY_SECTION_11_OF_THE_AVIATION_AND_MARITIME_SECURITY_ACT_1990("Destroying fixed platforms or endangering their safety (section 11 of the Aviation and Maritime Security Act 1990)", IndexOffenceGroupEnum.TERRORISM_GROUP),
  DESTROYING_OR_DAMAGING_PROPERTY_OTHER_THAN_AN_OFFENCE_OF_ARSON_SECTION_12_OF_THE_CRIMINAL_DAMAGE_ACT_1971("Destroying or damaging property other than an offence of arson (section 1(2) of the Criminal Damage Act 1971)", IndexOffenceGroupEnum.OTHER_GROUP),
  DESTROYING_DAMAGING_OR_ENDANGERING_SAFETY_OF_AIRCRAFT_SECTION_2_OF_THE_AVIATION_SECURITY_ACT_1982("Destroying, damaging or endangering safety of aircraft (section 2 of the Aviation Security Act 1982)", IndexOffenceGroupEnum.TERRORISM_GROUP),
  DRIVING_UNDER_THE_INFLUENCE_OF_DRINK_DRUGS("DRIVING UNDER THE INFLUENCE OF DRINK/DRUGS", IndexOffenceGroupEnum.MOTORING_OFFENCES_GROUP),
  DRIVING_WHILST_DISQUALIFIED("DRIVING WHILST DISQUALIFIED", IndexOffenceGroupEnum.MOTORING_OFFENCES_GROUP),
  DRUNK("DRUNK", IndexOffenceGroupEnum.OTHER_GROUP),
  ENDANGERING_SAFETY_AT_AERODROMES_UNDER_SECTION_1_OF_THE_AVIATION_AND_MARITIME_SECURITY_ACT_1990("Endangering safety at aerodromes (under section 1 of the Aviation and Maritime Security Act 1990)", IndexOffenceGroupEnum.TERRORISM_GROUP),
  ENDANGERING_THE_SAFETY_OF_RAILWAY_PASSENGERS_SECTION_32_OF_THE_OFFENCES_AGAINST_THE_PERSON_ACT_1861("Endangering the safety of railway passengers (section 32 of the Offences Against the Person Act 1861)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  ENGAGING_IN_SEXUAL_ACTIVITY_IN_THE_PRESENCE_OF_A_CHILD_SECTION_11_OF_THE_SEXUAL_OFFENCES_ACT_2003("Engaging in sexual activity in the presence of a child (section 11 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  ENGAGING_IN_SEXUAL_ACTIVITY_IN_THE_PRESENCE_OF_A_PERSON_WITH_A_MENTAL_DISORDER_IMPEDING_CHOICE_SECTION_32_OF_THE_SEXUAL_OFFENCES_ACT_2003("Engaging in sexual activity in the presence of a person with a mental disorder impeding choice (section 32 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  ENGAGING_IN_SEXUAL_ACTIVITY_IN_THE_PRESENCE_PROCURED_BY_INDUCEMENT_THREAT_OR_DECEPTION_OF_A_PERSON_WITH_A_MENTAL_DISORDER_SECTION_36_OF_THE_SEXUAL_OFFENCES_ACT_2003("Engaging in sexual activity in the presence, procured by inducement, threat or deception, of a person with a mental disorder (section 36 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  ESCAPE_LAWFUL_CUSTODY("ESCAPE LAWFUL CUSTODY", IndexOffenceGroupEnum.OTHER_GROUP),
  FAIL_TO_SURRENDER("FAIL TO SURRENDER", IndexOffenceGroupEnum.OTHER_GROUP),
  FAILURE_TO_PROVIDE_A_SPECIMEN("FAILURE TO PROVIDE A SPECIMEN", IndexOffenceGroupEnum.MOTORING_OFFENCES_GROUP),
  FAILURE_TO_RETURN_FROM_TEMPORARY_ABSENCE("FAILURE TO RETURN FROM TEMPORARY ABSENCE", IndexOffenceGroupEnum.OTHER_GROUP),
  FALSE_IMPRISONMENT("False imprisonment", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  FALSE_INSTRUMENTS("FALSE INSTRUMENTS", IndexOffenceGroupEnum.FRAUD_AND_FORGERY_GROUP),
  FALSE_STATEMENT_TO_A_PRISON_OFFICER("FALSE STATEMENT TO A PRISON OFFICER", IndexOffenceGroupEnum.OTHER_GROUP),
  FEMALE_GENITAL_MUTILATION_SECTION_1_OF_THE_FEMALE_GENITAL_MUTILATION_ACT_2003("Female genital mutilation (section 1 of the Female Genital Mutilation Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  FORGERY("FORGERY", IndexOffenceGroupEnum.FRAUD_AND_FORGERY_GROUP),
  FRAUD("FRAUD", IndexOffenceGroupEnum.FRAUD_AND_FORGERY_GROUP),
  FURNISHING_FALSE_INFORMATION("FURNISHING FALSE INFORMATION", IndexOffenceGroupEnum.FRAUD_AND_FORGERY_GROUP),
  GENOCIDE_CRIMES_AGAINST_HUMANITY_WAR_CRIMES_AND_RELATED_OFFENCES_OTHER_THAN_ONE_INVOLVING_MURDER_SECTION_51_OR_52_OF_THE_INTERNATIONAL_CRIMINAL_COURT_ACT_2001("Genocide, crimes against humanity, war crimes and related offences), other than one involving murder (section 51 or 52 of the International Criminal Court Act 2001)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  GOING_EQUIPED_TO_CHEAT("GOING EQUIPED TO CHEAT", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  GOING_EQUIPPED_FOR_STEALING("GOING EQUIPPED FOR STEALING", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  GROSS_INDECENCY("GROSS INDECENCY", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  GROSS_INDECENCY_WITH_A_CHILD("GROSS INDECENCY WITH A CHILD", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  HANDLING_STOLEN_GOODS("HANDLING STOLEN GOODS", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  HARRASSMENT("HARRASSMENT", IndexOffenceGroupEnum.OTHER_GROUP),
  HEALTH_AND_SAFTEY_AT_WORK_ACT("HEALTH AND SAFTEY AT WORK ACT", IndexOffenceGroupEnum.OTHER_GROUP),
  HI_JACKING("HI-JACKING", IndexOffenceGroupEnum.TERRORISM_GROUP),
  HIJACKING_SECTION_1_OF_THE_AVIATION_SECURITY_ACT_1982("Hijacking (section 1 of the Aviation Security Act 1982)", IndexOffenceGroupEnum.TERRORISM_GROUP),
  HIJACKING_OF_SHIPS_SECTION_9_OF_THE_AVIATION_AND_MARITIME_SECURITY_ACT_1990("Hijacking of ships (section 9 of the Aviation and Maritime Security Act 1990)", IndexOffenceGroupEnum.TERRORISM_GROUP),
  HOLDING_WARRANT("HOLDING WARRANT", IndexOffenceGroupEnum.OTHER_GROUP),
  HOSTAGE_TAKING_SECTION_1_OF_THE_TAKING_OF_HOSTAGES_ACT_1982("Hostage-taking (section 1 of the Taking of Hostages Act 1982)", IndexOffenceGroupEnum.TERRORISM_GROUP),
  ILLEGAL_IMMIGRANT_DETAINEE("ILLEGAL IMMIGRANT/DETAINEE", IndexOffenceGroupEnum.OTHER_GROUP),
  IMPORT_ERROR_SEE_COMMENTS_SFO("Import Error see comments (SFO)", IndexOffenceGroupEnum.NOT_APPLICABLE_GROUP),
  IMPORT_EXPORT_DRUG("IMPORT/EXPORT/DRUG", IndexOffenceGroupEnum.DRUG_OFFENCES_GROUP),
  IN_DEFAULT_OF_RECOGS("IN DEFAULT OF RECOGS", IndexOffenceGroupEnum.OTHER_GROUP),
  INCEST("INCEST", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  INCEST_BY_A_MAN_SECTION_10_OF_THE_SEXUAL_OFFENCES_ACT_1956("Incest by a man (section 10 of the Sexual Offences Act 1956)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  INCEST_BY_MAN_WITH_U13_GIRL("Incest by man with U13 girl", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  INCITE_CHILD_UNDER_13_TO_ENGAGE_IN_SEXUAL_ACTIVITY("incite child under 13 to engage in sexual activity", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  INCITING_A_CHILD_FAMILY_MEMBER_TO_ENGAGE_IN_SEXUAL_ACTIVITY_SECTION_26_OF_THE_SEXUAL_OFFENCES_ACT_2003("Inciting a child family member to engage in sexual activity (section 26 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  INCITING_GIRL_UNDER_16_TO_HAVE_INCESTUOUS_SEX_INT("INCITING GIRL UNDER 16 TO HAVE INCESTUOUS SEX INT", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  INDECENCY_BETWEEN_MALES("INDECENCY BETWEEN MALES", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  INDECENT_ASSAULT("INDECENT ASSAULT", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  INDECENT_ASSAULT_ON_A_CHILD("INDECENT ASSAULT ON A CHILD", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  INDECENT_ASSAULT_ON_A_MAN_SECTION_15_OF_THE_SEXUAL_OFFENCES_ACT_1956("Indecent assault on a man section 15 of the Sexual Offences Act 1956)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  INDECENT_ASSAULT_ON_A_WOMAN_SECTION_14_OF_THE_SEXUAL_OFFENCES_ACT_1956("Indecent assault on a woman (section 14 of the Sexual Offences Act 1956)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  INDECENT_CONDUCT_TOWARDS_YOUNG_CHILD_UNDER_SECTION_1_OF_THE_INDECENCY_WITH_CHILDREN_ACT_1960("Indecent conduct towards young child (under section 1 of the Indecency with Children Act 1960)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  INDECENT_EXPOSURE("INDECENT EXPOSURE", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  INDECENT_PHOTOGRAPHS("INDECENT PHOTOGRAPHS", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  INDECENT_PHOTOGRAPHS_OF_CHILDREN_SECTION_1_OF_THE_PROTECTION_OF_CHILDREN_ACT_1978("Indecent photographs of children (section 1 of the Protection of Children Act 1978)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  INDUCEMENT_THREAT_OR_DECEPTION_TO_PROCURE_SEXUAL_ACTIVITY_WITH_A_PERSON_WITH_A_MENTAL_DISORDER_SECTION_34_OF_THE_SEXUAL_OFFENCES_ACT_2003("Inducement, threat or deception to procure sexual activity with a person with a mental disorder (section 34 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  INFANTICIDE_SECTION_1_OF_THE_INFANTICIDE_ACT_1938("Infanticide (section 1 of the Infanticide Act 1938)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  INFLICT_GRIEVOUS_BODILY_HARM("INFLICT GRIEVOUS BODILY HARM", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  INTERCOURSE_WITH_GIRL_UNDER_THIRTEEN_SECTION_5_OF_THE_SEXUAL_OFFENCES_ACT_1956("Intercourse with girl under thirteen (section 5 of the Sexual Offences Act 1956)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  INTIMIDATION_OF_WITNESS("INTIMIDATION OF WITNESS", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  KEEPING_A_BROTHEL("KEEPING A BROTHEL", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  KIDNAPPING("Kidnapping", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  LIBEL("LIBEL", IndexOffenceGroupEnum.OTHER_GROUP),
  LIVING_OFF_PROSTITUTION("LIVING OFF PROSTITUTION", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  LOITERING("LOITERING", IndexOffenceGroupEnum.OTHER_GROUP),
  MAKE_OFF_WITHOUT_PAYING("MAKE OFF WITHOUT PAYING", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  MALICIOUS_DAMAGE("MALICIOUS DAMAGE", IndexOffenceGroupEnum.OTHER_GROUP),
  MALICIOUS_WOUNDING_INFLICTING_GBH_S20("Malicious Wounding (INFLICTING GBH) s20", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  MALICIOUSLY_ADMINISTERING_POISON_ETC_SO_AS_TO_ENDANGER_LIFE_OR_INFLICT_GRIEVOUS_BODILY_HARM_SECTION_23_OF_THE_OFFENCES_AGAINST_THE_PERSON_ACT_1861("Maliciously administering poison etc so as to endanger life or inflict grievous bodily harm (section 23 of the Offences Against the Person Act 1861)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  MANDATORY_MANSLAUGHTER("Mandatory Manslaughter", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  MANSLAUGHTER("Manslaughter", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  MANSLAUGHTER_D_R("Manslaughter D/R", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  MEETING_A_CHILD_FOLLOWING_SEXUAL_GROOMING_ETC_SECTION_15_OF_THE_SEXUAL_OFFENCES_ACT_2003("Meeting a child following sexual grooming etc (section 15 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  MINOR_FIREARM_OFFENCES("Minor firearm offences", IndexOffenceGroupEnum.OTHER_GROUP),
  MURDER("Murder", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  NO_FIREARM_LICENCE("NO FIREARM LICENCE", IndexOffenceGroupEnum.OTHER_GROUP),
  NO_TELEVISION_LICENCE("NO TELEVISION LICENCE", IndexOffenceGroupEnum.OTHER_GROUP),
  NON_PAYMENT_OF_CHILD_MAINTAINANCE("NON PAYMENT OF CHILD MAINTAINANCE", IndexOffenceGroupEnum.OTHER_GROUP),
  NON_PAYMENT_OF_COMMUNITY_CHARGE("NON PAYMENT OF COMMUNITY CHARGE", IndexOffenceGroupEnum.OTHER_GROUP),
  NON_PAYMENT_OF_RATES("NON PAYMENT OF RATES", IndexOffenceGroupEnum.OTHER_GROUP),
  NON_PAYMENT_OF_WIFE_MAINTENANCE_INC_WIFE_AND_CHILD("NON-PAYMENT OF WIFE MAINTENANCE (INC WIFE & CHILD)", IndexOffenceGroupEnum.OTHER_GROUP),
  NOT_APPLICABLE("Not Applicable", IndexOffenceGroupEnum.NOT_APPLICABLE_GROUP),
  NOT_SPECIFIED("Not Specified", IndexOffenceGroupEnum.NOT_SPECIFIED_GROUP),
  OBSCENE_PUBLICATIONS("OBSCENE PUBLICATIONS", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  OBSCENE_TELEPHONE_CALLS("OBSCENE TELEPHONE CALLS", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  OBSTRUCT_OR_RESIST_A_POLICE_CONSTABLE("OBSTRUCT OR RESIST A POLICE CONSTABLE", IndexOffenceGroupEnum.OTHER_GROUP),
  OBSTRUCTION("OBSTRUCTION", IndexOffenceGroupEnum.OTHER_GROUP),
  OBSTRUCTION_OF_COURT_PRISON_OFFICER("OBSTRUCTION OF COURT/PRISON OFFICER", IndexOffenceGroupEnum.OTHER_GROUP),
  OFFENCE_NOT_RECORDED("Offence not recorded", IndexOffenceGroupEnum.NOT_APPLICABLE_GROUP),
  OFFENCES_INVOLVING_THREATS_SECTION_13_OF_THE_AVIATION_AND_MARITIME_SECURITY_ACT_1990("Offences involving threats (section 13 of the Aviation and Maritime Security Act 1990)", IndexOffenceGroupEnum.TERRORISM_GROUP),
  OFFENCES_RELATING_TO_CHANNEL_TUNNEL_TRAINS_AND_THE_TUNNEL_SYSTEM_PART_II_OF_THE_CHANNEL_TUNNEL_SECURITY_ORDER_1994_SI_1994_570("Offences relating to Channel Tunnel trains and the tunnel system (Part II of the Channel Tunnel (Security) Order 1994 (SI 1994/570))", IndexOffenceGroupEnum.TERRORISM_GROUP),
  OFFICIAL_SECRETS_ACT("OFFICIAL SECRETS ACT", IndexOffenceGroupEnum.OTHER_GROUP),
  OTHER_ACTS_ENDANGERING_OR_LIKELY_TO_ENDANGER_SAFE_NAVIGATION_SECTION_12_OF_THE_AVIATION_AND_MARITIME_SECURITY_ACT_1990("Other acts endangering or likely to endanger safe navigation (section 12 of the Aviation and Maritime Security Act 1990)", IndexOffenceGroupEnum.TERRORISM_GROUP),
  OTHER_ACTS_ENDANGERING_OR_LIKELY_TO_ENDANGER_SAFETY_OF_AIRCRAFT_SECTION_3_OF_THE_AVIATION_SECURITY_ACT_1982("Other acts endangering or likely to endanger safety of aircraft (section 3 of the Aviation Security Act 1982)", IndexOffenceGroupEnum.TERRORISM_GROUP),
  OTHER_BURGLARY_OFFENCES("OTHER BURGLARY OFFENCES", IndexOffenceGroupEnum.BURGLARY_GROUP),
  OTHER_CHILD_PROSTITUTION("Other child prostitution", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  OTHER_CIVIL_OFFENCES("OTHER CIVIL OFFENCES", IndexOffenceGroupEnum.OTHER_GROUP),
  OTHER_CRIMINAL_OFFENCES("OTHER CRIMINAL OFFENCES", IndexOffenceGroupEnum.OTHER_GROUP),
  OTHER_DRIVING_OFFENCES("OTHER DRIVING OFFENCES", IndexOffenceGroupEnum.MOTORING_OFFENCES_GROUP),
  OTHER_DRUGS_OFFENCES("OTHER DRUGS OFFENCES", IndexOffenceGroupEnum.DRUG_OFFENCES_GROUP),
  OTHER_EXPLOSIVES_OFFENCES("Other explosives offences", IndexOffenceGroupEnum.TERRORISM_GROUP),
  OTHER_FRAUD_DECEPTION_FINANCIAL_OFFENCES("OTHER FRAUD/DECEPTION/FINANCIAL OFFENCES", IndexOffenceGroupEnum.FRAUD_AND_FORGERY_GROUP),
  OTHER_OFFENCES_AGAINST_THE_PERSON("Other offences against the person", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  OTHER_SERIOUS_CHILD_SEX_OFFENCES("Other Serious child sex offences", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  OTHER_SERIOUS_VIOLENT_OFFENCE("Other serious violent offence", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  OTHER_SEX_TRAFFICKING("Other sex trafficking", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  OTHER_SEXUAL_OFFENCES("OTHER SEXUAL OFFENCES", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  OTHER_THEFT_OFFENCES("OTHER THEFT OFFENCES", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  OTHER_VIOLENT_OFFENCES("OTHER VIOLENT OFFENCES", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  PARENTS_FINE_FOR_CHILD("PARENTS FINE FOR CHILD", IndexOffenceGroupEnum.OTHER_GROUP),
  PAYING_FOR_SEXUAL_SERVICES_OF_A_CHILD_SECTION_47_OF_THE_SEXUAL_OFFENCES_ACT_2003("Paying for sexual services of a child (section 47 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  PERJURY("PERJURY", IndexOffenceGroupEnum.OTHER_GROUP),
  PERMITTING_GIRL_UNDER_THIRTEEN_TO_USE_PREMISES_FOR_INTERCOURSE_SECTION_25_OF_THE_SEXUAL_OFFENCES_ACT_1956("Permitting girl under thirteen to use premises for intercourse (section 25 of the Sexual Offences Act 1956)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  PLACING_EXPLOSIVES_ETC_WITH_INTENT_TO_DO_BODILY_INJURY_SECTION_30_OF_THE_OFFENCES_AGAINST_THE_PERSON_ACT_1861("Placing explosives etc with intent to do bodily injury (section 30 of the Offences Against the Person Act 1861)", IndexOffenceGroupEnum.TERRORISM_GROUP),
  POSSESSION_DRUG("POSSESSION DRUG", IndexOffenceGroupEnum.DRUG_OFFENCES_GROUP),
  POSSESSION_DRUGS_WITH_INTENT_TO_SUPPLY("POSSESSION DRUGS WITH INTENT TO SUPPLY", IndexOffenceGroupEnum.DRUG_OFFENCES_GROUP),
  POSSESSION_OF_A_FIREARM("Possession of a Firearm", IndexOffenceGroupEnum.OTHER_GROUP),
  POSSESSION_OF_AN_OFFENSIVE_WEAPON("POSSESSION OF AN OFFENSIVE WEAPON", IndexOffenceGroupEnum.OTHER_GROUP),
  POSSESSION_OF_FIREARM_AT_TIME_OF_COMMITTING_OR_BEING_ARRESTED_FOR_OFFENCE_SPECIFIED_IN_SCHEDULE_1_TO_THAT_ACT_SECTION_172_OF_THE_FIREARMS_ACT_1968("Possession of firearm at time of committing or being arrested for offence specified in Schedule 1 to that Act (section 17(2) of the Firearms Act 1968)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  POSSESSION_OF_FIREARM_WITH_INTENT_TO_CAUSE_FEAR_OF_VIOLENCE_SECTION_16A_OF_THE_FIREARMS_ACT_1968("Possession of firearm with intent to cause fear of violence (section 16A of the Firearms Act 1968)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  POSSESSION_OF_FIREARM_WITH_INTENT_TO_ENDANGER_LIFE_SECTION_16_OF_THE_FIREARMS_ACT_1968("Possession of firearm with intent to endanger life (section 16 of the Firearms Act 1968)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  PREVENTION_OF_TERRORISM_ACT("PREVENTION OF TERRORISM ACT", IndexOffenceGroupEnum.TERRORISM_GROUP),
  PROCESSING_A_DOCUMENT_LIKELY_TO_BE_USEFUL_TO_A_PERSON_COMMITTING_PREPARING_AN_ACT_OF_TERRORISM("processing a document likely to be useful to a person committing/ preparing an act of terrorism", IndexOffenceGroupEnum.TERRORISM_GROUP),
  PROCURATION("PROCURATION", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  PROCURING_ILLEGAL_ABORTION_CONCEALMENT_OF_BIRTH("PROCURING ILLEGAL ABORTION/CONCEALMENT OF BIRTH", IndexOffenceGroupEnum.OTHER_GROUP),
  PRODUCTION_DRUG("PRODUCTION DRUG", IndexOffenceGroupEnum.DRUG_OFFENCES_GROUP),
  PROSTITUTION("PROSTITUTION", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  PROSTITUTION_INTERCOURSE_IND_ASS_ON_GIRL_UNDER_16("PROSTITUTION/INTERCOURSE/IND ASS ON GIRL UNDER 16", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  PUBLIC_ORDER_OFFENCES("Public Order Offences", IndexOffenceGroupEnum.OTHER_GROUP),
  RAILWAY_OFFENCES("Railway Offences", IndexOffenceGroupEnum.OTHER_GROUP),
  RAPE_SECTION_1_OF_THE_SEXUAL_OFFENCES_ACT_1956("Rape (section 1 of the Sexual Offences Act 1956)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  RAPE_SECTION_1_OF_THE_SEXUAL_OFFENCES_ACT_2003("Rape (section 1 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  RAPE_OF_A_CHILD_UNDER_13_SECTION_5_OF_THE_SEXUAL_OFFENCES_ACT_2003("Rape of a child under 13 (section 5 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  RECEIVING_STOLEN_GOODS("RECEIVING STOLEN GOODS", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  RECKLESS_DRIVING("RECKLESS DRIVING", IndexOffenceGroupEnum.MOTORING_OFFENCES_GROUP),
  RIOT_SECTION_1_OF_THE_PUBLIC_ORDER_ACT_1986("Riot (section 1 of the Public Order Act 1986)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  RIOTING("RIOTING", IndexOffenceGroupEnum.OTHER_GROUP),
  ROAD_TRAFFIC_ACTNO_INS_LIC_LIGHTS_BALD_TYRES_ETC("ROAD TRAFFIC ACT(NO INS/LIC/LIGHTS/BALD TYRES ETC)", IndexOffenceGroupEnum.MOTORING_OFFENCES_GROUP),
  ROBBERY("ROBBERY", IndexOffenceGroupEnum.ROBBERY_GROUP),
  ROBBERY_OR_ASSAULT_WITH_INTENT_TO_ROB_SECTION_8_OF_THE_THEFT_ACT_1968("Robbery or assault with intent to rob (section 8 of the Theft Act 1968)", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  S38_BREACH_OF_LICENCE_FOR_SHORT_TERM_PRISONERS("S38 BREACH OF LICENCE FOR SHORT TERM PRISONERS", IndexOffenceGroupEnum.OTHER_GROUP),
  SEC_40_CONVICTIONS_DURING_ORIGINAL_SENTENCE("SEC 40 CONVICTIONS DURING ORIGINAL SENTENCE", IndexOffenceGroupEnum.OTHER_GROUP),
  SEIZING_OR_EXERCISING_CONTROL_OF_FIXED_PLATFORMS_SECTION_10_OF_THE_AVIATION_AND_MARITIME_SECURITY_ACT_1990("Seizing or exercising control of fixed platforms (section 10 of the Aviation and Maritime Security Act 1990)", IndexOffenceGroupEnum.TERRORISM_GROUP),
  SERIOUS_FIREARMS_OFFENCES_SFO("Serious firearms offences (SFO)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  SERIOUS_SEXUAL_OFFENCE_MIGRATED_DATA("Serious Sexual Offence - Migrated Data", IndexOffenceGroupEnum.NOT_APPLICABLE_GROUP),
  SERIOUS_VIOLENT_OFFENCE_MIGRATED_DATA("Serious Violent Offence - Migrated Data", IndexOffenceGroupEnum.NOT_APPLICABLE_GROUP),
  SETTING_TRAP_WITH_INTENT_TO_CAUSE_GRIEVOUS_BODILY_HARM("Setting trap with intent to cause grievous bodily harm", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  SEXUAL_ACTIVITY_WITH_A_CHILD_SECTION_9_OF_THE_SEXUAL_OFFENCES_ACT_2003("Sexual activity with a child (section 9 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  SEXUAL_ACTIVITY_WITH_A_CHILD_FAMILY_MEMBER_SECTION_25_OF_THE_SEXUAL_OFFENCES_ACT_2003("Sexual activity with a child family member (section 25 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  SEXUAL_ACTIVITY_WITH_A_PERSON_WITH_A_MENTAL_DISORDER_IMPEDING_CHOICE_SECTION_30_OF_THE_SEXUAL_OFFENCES_ACT_2003("Sexual activity with a person with a mental disorder impeding choice (section 30 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  SEXUAL_ACTIVITY_WITH_FEMALE_PERSON_WITH_A_MENTAL_DISORDER_LEARNING_DISABILITY_CARE_WORKER_PENETRATION_OF_ANUS_VAGINA_MOUTH_BY_PENIS_PART_OF_BODY("Sexual activity with female person with a mental disorder/learning disability - care worker - penetration of anus, vagina, mouth by penis/part of body", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  SEXUAL_ACTIVITY_WITH_MALE_PERSON_WITH_A_MENTAL_DISORDER_LEARNING_DISABILITY_CARE_WORKER_PENETRATION_OF_ANUS_VAGINA_MOUTH_BY_PENIS_PART_OF_BODY("Sexual activity with male person with a mental disorder/learning disability - care worker - penetration of anus, vagina, mouth by penis/part of body", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  SEXUAL_ASSAULT_SECTION_3_OF_THE_SEXUAL_OFFENCES_ACT_2003("Sexual assault (section 3 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  SEXUAL_ASSAULT_OF_A_CHILD_UNDER_13_SECTION_7_OF_THE_SEXUAL_OFFENCES_ACT_2003("Sexual assault of a child under 13 (section 7 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  SOLICITING_MURDER_SECTION_4_OF_THE_OFFENCES_AGAINST_THE_PERSON_ACT_1861("Soliciting murder (section 4 of the Offences against the Person Act 1861)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  SOLICITING_IMPORTUNING_MALES("SOLICITING/IMPORTUNING (MALES)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  STALK_A_PERSON_CAUSING_FEAR_OF_VIOLENCE("STALK A PERSON CAUSING FEAR OF VIOLENCE", IndexOffenceGroupEnum.OTHER_GROUP),
  SUPPLYING_DRUGS("SUPPLYING DRUGS", IndexOffenceGroupEnum.DRUG_OFFENCES_GROUP),
  TAKING_AND_DRIVING_AWAY("TAKING AND DRIVING AWAY", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  THEFT("THEFT", IndexOffenceGroupEnum.THEFT_AND_HANDLING_GROUP),
  THREATENING_DISORDERLY_BEHAVIOUR("THREATENING / DISORDERLY BEHAVIOUR", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  THREATS_TO_KILL_SECTION_16_OF_THE_OFFENCES_AGAINST_THE_PERSON_ACT_1861("Threats to kill (section 16 of the Offences against the Person Act 1861)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  TORTURE_SECTION_134_OF_THE_CRIMINAL_JUSTICE_ACT_1988("Torture (section 134 of the Criminal Justice Act 1988)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_SERIOUS_GROUP),
  TRAFFICKING_INTO_THE_UK_FOR_SEXUAL_EXPLOITATION_SECTION_57_OF_THE_SEXUAL_OFFENCES_ACT_2003("Trafficking into the UK for sexual exploitation (section 57 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  TRAFFICKING_OUT_OF_THE_UK_FOR_SEXUAL_EXPLOITATION_SECTION_59_OF_THE_SEXUAL_OFFENCES_ACT_2003("Trafficking out of the UK for sexual exploitation (section 59 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  TRAFFICKING_WITHIN_THE_UK_FOR_SEXUAL_EXPLOITATION_SECTION_58_OF_THE_SEXUAL_OFFENCES_ACT_2003("Trafficking within the UK for sexual exploitation (section 58 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  TREASON("TREASON", IndexOffenceGroupEnum.OTHER_GROUP),
  TRESPASS("TRESPASS", IndexOffenceGroupEnum.OTHER_GROUP),
  TRESPASS_WITH_INTENT("TRESPASS WITH INTENT", IndexOffenceGroupEnum.BURGLARY_GROUP),
  TRESPASS_WITH_INTENT_TO_COMMIT_A_SEXUAL_OFFENCE_SECTION_63_OF_THE_SEXUAL_OFFENCES_ACT_2003("Trespass with intent to commit a sexual offence (section 63 of the Sexual Offences Act 2003)", IndexOffenceGroupEnum.SEXUAL_OFFENCE_GROUP),
  UAL_OFFENCE("UAL Offence", IndexOffenceGroupEnum.OTHER_GROUP),
  UNKNOWN_MIGRATED("Unknown - Migrated", IndexOffenceGroupEnum.NOT_APPLICABLE_GROUP),
  UNLAWFUL_SEXUAL_INTERCOURSE("UNLAWFUL SEXUAL INTERCOURSE", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  UNLAWFUL_SEXUAL_INTERCOURSE_GIRL_13_16("UNLAWFUL SEXUAL INTERCOURSE GIRL 13-16", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  UNLAWFUL_SEXUAL_INTERCOURSE_GIRL_UNDER_13("UNLAWFUL SEXUAL INTERCOURSE GIRL UNDER 13", IndexOffenceGroupEnum.SEXUAL_OFFENCE_SERIOUS_GROUP),
  USE_OF_FIREARM_TO_RESIST_ARREST_SECTION_171_OF_THE_FIREARMS_ACT_1968("Use of firearm to resist arrest (section 17(1) of the Firearms Act 1968)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  USING_CHLOROFORM_ETC_TO_COMMIT_OR_ASSIST_IN_THE_COMMITTING_OF_ANY_INDICTABLE_OFFENCE_SECTION_22_OF_THE_OFFENCES_AGAINST_THE_PERSON_ACT_1861("Using chloroform etc to commit or assist in the committing of any indictable offence (section 22 of the Offences Against the Person Act 1861)", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  USING_EXPLOSIVES_ETC_WITH_INTENT_TO_DO_GRIEVOUS_BODILY_HARM_SECTION_29_OF_THE_OFFENCES_AGAINST_THE_PERSON_ACT_1861("Using explosives etc with intent to do grievous bodily harm (section 29 of the Offences Against the Person Act 1861)", IndexOffenceGroupEnum.TERRORISM_GROUP),
  VAGRANCY("VAGRANCY", IndexOffenceGroupEnum.OTHER_GROUP),
  VARIOUS_MIGRATED_DATA("Various - Migrated Data", IndexOffenceGroupEnum.NOT_APPLICABLE_GROUP),
  VEHICLE_INTERFERENCE("VEHICLE INTERFERENCE", IndexOffenceGroupEnum.MOTORING_OFFENCES_GROUP),
  VIOLENT_DISORDER("VIOLENT DISORDER", IndexOffenceGroupEnum.VIOLENCE_AGAINST_THE_PERSON_GROUP),
  WASTING_POLICE_TIME("Wasting Police time", IndexOffenceGroupEnum.OTHER_GROUP),
  WOUNDING_WITH_INTENT_TO_CAUSE_GRIEVOUS_BODILY_HARM("Wounding with intent to cause grievous bodily harm", IndexOffenceGroupEnum.NOT_SPECIFIED_GROUP)
}
