---
generic-service:
  nameOverride: manage-recalls-api

  replicaCount: 4

  image:
    repository: quay.io/hmpps/manage-recalls-api
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: manage-recalls-cert
    # which cluster are we on: live-1 is blue, live is green
    contextColour: green
    annotations:
      external-dns.alpha.kubernetes.io/aws-weight: "100"
      nginx.ingress.kubernetes.io/limit-rpm: "200"

  livenessProbe:
    httpGet:
      path: /health/liveness
      port: metrics
  readinessProbe:
    httpGet:
      path: /health/readiness
      port: metrics

  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    GOTENBERG_ENDPOINT_URL: http://manage-recalls-api-gotenberg
    SENTRY_IGNORED_EXCEPTIONS_FOR_TYPE: uk.gov.justice.digital.hmpps.managerecallsapi.config.VirusFoundException,org.springframework.security.web.firewall.RequestRejectedException,org.springframework.web.HttpMediaTypeNotAcceptableException,uk.gov.justice.digital.hmpps.managerecallsapi.config.ClientTimeoutException
    CLAMAV_HOSTNAME: manage-recalls-api-clamav
    CLAMAV_PORT: 3310

  namespace_secrets:
    manage-recalls-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /prometheus
    metricsPort: 8081

generic-prometheus-alerts:
  targetApplication: manage-recalls-api
