---
generic-service:
  nameOverride: manage-recalls-api

  replicaCount: 4

  image:
    repository: quay.io/hmpps/manage-recalls-api
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: manage-recalls-api-cert
    # which cluster are we on: live-1 is blue, live is green
    contextColour: blue


  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    GOTENBERG_ENDPOINT_URL: http://manage-recalls-api-gotenberg
    SENTRY_IGNORED_EXCEPTIONS_FOR_TYPE: org.springframework.security.web.firewall.RequestRejectedException,uk.gov.justice.digital.hmpps.managerecallsapi.service.VirusFoundException
    CLAMAV_HOSTNAME: manage-recalls-api-clamav
    CLAMAV_PORT: 3310

  namespace_secrets:
    manage-recalls-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /prometheus

generic-prometheus-alerts:
  targetApplication: manage-recalls-api
