---
generic-service:
  nameOverride: manage-recalls-api

  replicaCount: 4

  image:
    repository: quay.io/hmpps/manage-recalls-api
    tag: app_version    # override at deployment time
    port: 8080

  extraDashboardTags:
    - ppud-replacement
    - manage-recalls

  ingress:
    enabled: true
    host: app-hostname.local    # override per environment
    tlsSecretName: manage-recalls-api-cert
    path: /

  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    GOTENBERG_ENDPOINT_URL: http://manage-recalls-api-gotenberg

  namespace_secrets:
    manage-recalls-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"
      API_CLIENT_ID: "API_CLIENT_ID"
      API_CLIENT_SECRET: "API_CLIENT_SECRET"
    manage-recalls-database:
      POSTGRES_HOST: "host"
      POSTGRES_DBNAME: "name"
      POSTGRES_USERNAME: "username"
      POSTGRES_PASSWORD: "password"
    manage-recalls-s3-bucket:
      S3_ACCESS_KEY: "access_key_id"
      S3_SECRET_KEY: "secret_access_key"
      S3_BUCKET_NAME: "bucket_name"

generic-prometheus-alerts:
  targetApplication: manage-recalls-api
  alertSeverity: ppud-replacement-alerts
