---
# Per environment values which override defaults in manage-recalls-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-recalls-api-preprod.hmpps.service.justice.gov.uk
    tlsSecretName: ppud-replacement-preprod-cert

  env:
    OAUTH_ENDPOINT_URL: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in-preprod.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json
    PRISONERSEARCH_ENDPOINT_URL: https://prisoner-offender-search-preprod.prison.service.justice.gov.uk
    MANAGE_RECALLS_API_BASE_URI: https://manage-recalls-api-preprod.hmpps.service.justice.gov.uk
