---
# Per environment values which override defaults in manage-recalls-api/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: manage-recalls-api.hmpps.service.justice.gov.uk
    tlsSecretName: ppud-replacement-prod-cert

  env:
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json
    PRISONERSEARCH_ENDPOINT_URL: https://prisoner-offender-search.prison.service.justice.gov.uk
    MANAGE_RECALLS_API_BASE_URI: https://manage-recalls-api.hmpps.service.justice.gov.uk
    PRISONREGISTER_ENDPOINT_URL:  https://prison-register.hmpps.service.justice.gov.uk
    COURTREGISTER_ENDPOINT_URL:  https://court-register.hmpps.service.justice.gov.uk
    SENTRY_DSN: https://ea6c4e03abe840319aee1bc1b2a6a58a@o345774.ingest.sentry.io/5940644
    SENTRY_ENVIRONMENT: PROD

  namespace_secrets:
    manage-recalls-database:
      POSTGRES_HOST: "host"
      POSTGRES_DBNAME: "name"
      POSTGRES_USERNAME: "username"
      POSTGRES_PASSWORD: "password"
    manage-recalls-s3-bucket:
      S3_ACCESS_KEY: "access_key_id"
      S3_SECRET_KEY: "secret_access_key"
      S3_BUCKET_NAME: "bucket_name"

generic-prometheus-alerts:
  alertSeverity: ppud-replacement-prod
  extraDashboardTags:
    - ppud-replacement
    - manage-recalls
    - prod
