---
# Per environment values which override defaults in manage-recalls-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-recalls-api-dev.hmpps.service.justice.gov.uk
    tlsSecretName: ppud-replacement-dev-cert
    # which cluster are we on: live-1 is blue, live is green
    contextColour: blue

  env:
    OAUTH_ENDPOINT_URL: https://sign-in-dev.hmpps.service.justice.gov.uk/auth
    SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI: https://sign-in-dev.hmpps.service.justice.gov.uk/auth/.well-known/jwks.json
    PRISONERSEARCH_ENDPOINT_URL: https://prisoner-offender-search-dev.prison.service.justice.gov.uk
    MANAGE_RECALLS_API_BASE_URI: https://manage-recalls-api-dev.hmpps.service.justice.gov.uk
    PRISONREGISTER_ENDPOINT_URL:  https://prison-register-dev.hmpps.service.justice.gov.uk
    SENTRY_ENVIRONMENT: DEV

generic-prometheus-alerts:
  extraDashboardTags:
    - ppud-replacement
    - manage-recalls
    - dev
