---
# Per environment values which override defaults in manage-recalls-api/values.yaml

generic-service:
  replicaCount: 2

  ingress:
    host: manage-recalls-api-dev.hmpps.service.justice.gov.uk

generic-prometheus-alerts:
  alertSeverity: digital-prison-service-dev
