---
# Per environment values which override defaults in manage-recalls-ui/values.yaml

generic-service:
  ingress:
    host: manage-recalls-api-new-dev.hmpps.service.justice.gov.uk
    tlsSecretName: manage-recalls-cert

  namespace_secrets:
    manage-recalls-api-database:
      POSTGRES_HOST: "host"
      POSTGRES_DBNAME: "name"
      POSTGRES_USERNAME: "username"
      POSTGRES_PASSWORD: "password"
    manage-recalls-api-s3-bucket:
      S3_ACCESS_KEY: "access_key_id"
      S3_SECRET_KEY: "secret_access_key"
      S3_BUCKET_NAME: "bucket_name"

generic-prometheus-alerts:
  extraDashboardTags:
    - manage-recalls
    - dev
